apiVersion: 1

datasources:
  - name: resonance_prometheus
    type: prometheus
    uid: resonance-prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false
