{
 "title": "Resonance Dashboard",
 "description": "Overall Metric for resonance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Auth Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "auth_service_http_requests_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "auth_service_request_duration_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "user_service_http_requests_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "user_service_request_duration_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Match Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "match_service_http_requests_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "match_service_request_duration_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interaction Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "interaction_service_http_requests_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "interaction_service_request_duration_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Music Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "music_service_http_requests_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "music_service_request_duration_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chat Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "chat_service_http_requests_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "chat_service_request_duration_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}